# Generated by Django 2.0 on 2019-11-16 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20191114_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('suite', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='adress',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='address', to='posts.Address'),
            preserve_default=False,
        ),
    ]
